parser: '@typescript-eslint/parser'
extends:
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/indent': [error, 2]
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/no-namespace':
    - error
    - allowDeclarations: true
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-member-accessibility': off
