variables:
  AWS_ACCESS_KEY_ID: "$CI_ONLY_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "$CI_ONLY_AWS_SECRET_ACCESS_KEY"

stages:
  - install
  - build
  - deploy
  - publish

Install:
  stage: install
  image: node:lts-alpine
  cache:
    paths:
      - .npm/
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

Install:Deploy:
  stage: install
  image: node:lts-alpine
  cache:
    paths:
      - .npm/
  script:
    - npm ci --production
  artifacts:
    paths:
      - node_modules/

Test:
  stage: build
  image: node:lts-alpine
  script:
    - npm start lint
    - npm start check-types
    - npm start test
  dependencies:
    - Install

.deploy_template: &deploy
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint: [""]
  script:
    - terraform init
    - terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT
    - terraform apply -auto-approve -var VERSION=$CI_COMMIT_SHA

.publish_template: &publish
  stage: publish
  image: docker:stable
  services:
    - docker:dind
  dependencies:
    - Install:Deploy
  script:
    - $(docker run -i --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY infrastructureascode/aws-cli:1.16.111 aws ecr get-login --no-include-email --region us-east-1 | tr -d "\r\n")
    - docker build -t salte-ci-api .
    - docker tag salte-ci-api 853196007801.dkr.ecr.us-east-1.amazonaws.com/salte-ci-api-$ENVIRONMENT:$CI_COMMIT_SHA
    - docker push 853196007801.dkr.ecr.us-east-1.amazonaws.com/salte-ci-api-$ENVIRONMENT:$CI_COMMIT_SHA

Deploy to Alpha:
  <<: *deploy
  variables:
    ENVIRONMENT: alpha
    TF_VAR_BITBUCKET_CLIENT_ID: "$BITBUCKET_CLIENT_ID"
    TF_VAR_BITBUCKET_CLIENT_SECRET: "$BITBUCKET_CLIENT_SECRET"
    TF_VAR_GITHUB_CLIENT_ID: "$GITHUB_CLIENT_ID"
    TF_VAR_GITHUB_CLIENT_SECRET: "$GITHUB_CLIENT_SECRET"
    TF_VAR_GITLAB_CLIENT_ID: "$GITLAB_CLIENT_ID"
    TF_VAR_GITLAB_CLIENT_SECRET: "$GITLAB_CLIENT_SECRET"
  environment:
    name: alpha
    url: https://api.alpha.salte.ci
  only:
    - alpha

Publish to Alpha:
  <<: *publish
  variables:
    ENVIRONMENT: alpha
  only:
    - alpha

Deploy to Live:
  <<: *deploy
  variables:
    ENVIRONMENT: live
    TF_VAR_BITBUCKET_CLIENT_ID: "$BITBUCKET_CLIENT_ID"
    TF_VAR_BITBUCKET_CLIENT_SECRET: "$BITBUCKET_CLIENT_SECRET"
    TF_VAR_GITHUB_CLIENT_ID: "$GITHUB_CLIENT_ID"
    TF_VAR_GITHUB_CLIENT_SECRET: "$GITHUB_CLIENT_SECRET"
    TF_VAR_GITLAB_CLIENT_ID: "$GITLAB_CLIENT_ID"
    TF_VAR_GITLAB_CLIENT_SECRET: "$GITLAB_CLIENT_SECRET"
  environment:
    name: live
    url: https://api.salte.ci
  only:
    - live

Publish to Live:
  <<: *publish
  variables:
    ENVIRONMENT: live
  only:
    - live
